// <auto-generated />
using System;
using EDScenicRouteWeb.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace EDScenicRouteWeb.Server.Data.Migrations
{
    [DbContext(typeof(GalacticSystemContext))]
    [Migration("20200831103707_PoiBodyLatLong")]
    partial class PoiBodyLatLong
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("EDScenicRouteWeb.Server.Models.GalacticPOI", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Body")
                        .HasMaxLength(150);

                    b.Property<float>("DistanceFromSol");

                    b.Property<string>("GalMapSearch")
                        .HasMaxLength(600);

                    b.Property<string>("GalMapUrl")
                        .HasMaxLength(1000);

                    b.Property<float?>("Latitude");

                    b.Property<float?>("Longitude");

                    b.Property<string>("Name")
                        .HasColumnType("VARCHAR(200)")
                        .HasMaxLength(200);

                    b.Property<int>("Type");

                    b.Property<float>("X")
                        .HasColumnName("Coordinates_X");

                    b.Property<float>("Y")
                        .HasColumnName("Coordinates_Y");

                    b.Property<float>("Z")
                        .HasColumnName("Coordinates_Z");

                    b.HasKey("Id");

                    b.ToTable("GalacticPOIs");
                });

            modelBuilder.Entity("EDScenicRouteWeb.Server.Models.GalacticSystem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .HasColumnType("VARCHAR(200) UNIQUE")
                        .HasMaxLength(200);

                    b.Property<float>("X")
                        .HasColumnName("Coordinates_X");

                    b.Property<float>("Y")
                        .HasColumnName("Coordinates_Y");

                    b.Property<float>("Z")
                        .HasColumnName("Coordinates_Z");

                    b.HasKey("Id");

                    b.ToTable("GalacticSystems");
                });
#pragma warning restore 612, 618
        }
    }
}
